version: "3"
services:
  hubbit-frontend:
    build:
      context: frontend
      dockerfile: dev.Dockerfile
    environment:
      BACKEND_ADDRESS: http://hubbit-backend:8080
    ports:
      - ${FRONTEND_PORT}:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules

  hubbit-backend:
    build:
      context: backend
      dockerfile: dev.Dockerfile
    environment:
      PORT: 8080
      DATABASE_URL: postgres://hubbit:hubbit@hubbit-db/hubbit
      REDIS_URL: redis://hubbit-redis:6379
      GAMMA_API_KEY: hubbit
      GAMMA_CLIENT_ID: hubbit
      GAMMA_CLIENT_SECRET: hubbit
      GAMMA_URL: https://auth.chalmers.it
      GAMMA_REDIRECT_URI: http://localhost:3000/api/auth/gamma/callback
      COOKIE_SECRET: vVQvsmpCkHLuleJthaEd5KhCC23mnW3W5RGSNGQOru6Y32VBrddDJEMNSXGXiKeqWhTEOAQRlfYtYjbuLMY1N2PuDbOaMzx7UPpt6Ejnm2Rq4C3Wwew8wlLbMHOt14SQ
      COOKIE_SECURE: true
      RUST_LOG: ${BACKEND_LOG_LEVEL}
      GROUP_WHITELIST: ${GROUP_WHITELIST}
    ports:
      - ${BACKEND_PORT}:8080
    volumes:
      - ./backend:/app
      - /app/target
    depends_on:
      - "hubbit-db"
    command: ["./wait-for-postgres.sh", "hubbit-db", "${PG_PASSWORD}", "${PG_USERNAME}", "sh", "-c", "cargo sqlx migrate run && cargo watch -x run"]

  hubbit-db:
    image: postgres:13.2
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - ${PG_LOCAL_PORT}:5432

  hubbit-redis:
    image: redis:6.2
    ports:
      - ${REDIS_PORT}:6379

  adminer:
    image: adminer
    ports:
      - ${ADMINER_PORT}:8080

  redis-ui:
    image: patrikx3/p3x-redis-ui:2023.10.243
    ports:
      - ${REDIS_UI_PORT}:7843
    volumes:
      - /settings
